### ISSUE TITLE
Open dev theme on start

### ISSUE THREAD

**Issue by estrattonbailey** [the-couch/slater#1]
Would be cool to add a command to open a particular theme by `id`, using the configured themes in `slater.config.js`.

Could be a flag on watch as well i.e. during development: `slater watch --theme dev --open`

**Comment by iamkevingreen** [comment]
Since we have the theme ID and the shopify url this should be pretty easy to surface in the terminal after the start

`https://www.shop-url.myshopify.com/?fts=0&preview_theme_id=########`
