### ISSUE TITLE
Bundle assets for production when running the build command

### ISSUE THREAD

**Issue by jack-pallot** [the-couch/slater#101]
Hi,

I'm trying to work out a way to run the ```slater build``` command and have it minify the CSS and JS, as well as apply the autoprefixer and babel transforms. The reason being, it makes cross browser testing significantly easier, because you can test the output without having to run a full build and sync. Perhaps if running ```slater build``` added production ready copies inside the /src directory with the same filenames? That way everything would work as it does currently, with the benefit of being able to test the modified production assets before you run a deploy command.

Alternatively, adding a second watch command could work, such as watch:dev and watch:production? With the production command building the assets on save to make debugging easier. Any ideas would be appreciated.

**Comment by iamkevingreen** [comment]
So if you run build, you can selectively [sync](https://github.com/the-couch/slater#sync) the files you want into production? Is that what you're asking?

**Comment by jack-pallot** [comment]
This was actually an issue with a dependency from NPM not being transpiled. I thought that the build command wasn't working properly. This can be closed now as the build command does work as expected (minifying, transpiling with babel, running autoprefixer etc).
