### ISSUE TITLE
Is this still being maintained now that The Couch is defunct?

### ISSUE THREAD

**Issue by joniler** [the-couch/slater#109]
Seeing that The Couch is defunct now and am concerned about the maintenance of this project. Will this still be actively maintained, or would it make sense to fork this and build a new community around it? I'm not seeing active replies to issues or pull requests, and the last commit was 4 months ago. 

I'm actively building both a Vue and React starter theme with their own component libraries using Slater as a webpack base, and if the project needs new active maintainers, I think this should be discussed so that this wonderful project can live on even though the company who made it isn't. It's an awesome, modern tool for building Shopify themes.

**Comment by iamkevingreen** [comment]
@joniler The core tooling does indeed do it's job, so there isn't a whole lot that changes there, things like Shopify deployment and theme building hasn't in the way changed a lot over the last 4-8 years so all of that baseline stuff is still good. The part that's not really developed is the `theme` itself that was always meant to be a starting point for our internal couch projects. The rest of the tooling is fairly stable and intact, if you're using it currently theres no reason it wouldn't work in the future. As you're most likely not updating slater during development either. 

I am happy to open it up for other people that would like to contribute it, my only reason for not updating is I've been working mostly on headless builds only so less Shopify theme love. Theres also a number of forks that do things like remove the theme entirely and focus only on the tooling so lots of options out there for compiling Shopify sites and deployment.

**Comment by joniler** [comment]
@iamkevingreen Thanks for the reply! Once I'm a little further along with my Vue/React base themes, I'll get in touch with you. Cheers!
