### ISSUE TITLE
Build/Watch Error Windows

### ISSUE THREAD

**Issue by waywardm** [the-couch/slater#11]
I have followed the read me instructions however I receive the following errors when trying to build or watch using slater command on windows.

Am I missing something?

![slater1](https://user-images.githubusercontent.com/12498554/57022533-56f60980-6c27-11e9-989e-21908b02c951.JPG)
![slater2](https://user-images.githubusercontent.com/12498554/57022542-59586380-6c27-11e9-87a6-50979322e644.JPG)
![slater3](https://user-images.githubusercontent.com/12498554/57022550-5bbabd80-6c27-11e9-96a2-b4a0731389c4.JPG)

**Comment by waywardm** [comment]
Seems to be some issue with the path, this is using the couch theme as I haven't progressed to actually moving my theme yet.

**Comment by iamkevingreen** [comment]
@waywardm  looking into this, it's an importing error in our scripts, I think a config is missing somewhere.

**Comment by estrattonbailey** [comment]
@waywardm @iamkevingreen the first and second stack trace are probably unrelated.

The first is originating [here](https://github.com/the-couch/slater/blob/master/packages/slater/index.js#L173). `config.in` and `config.out` should be already set by default to `/src` and `/build`. So the missing piece there is probably the `file` argument, which is being emitted by the `change` event from Chokidar.

I'm not familiar with Windows. Is there a possibility that the file system is reporting the file change event strangely?

As to the second, it looks like `/src/scripts/index.js` doesn't exist. If your javascript entry file exists elsewhere, you can specify it like:

```javascript
module.exports = {
  // etc
  assets: {
    in: '/path/to/index.js'
  },
  // etc
}
```

Definitely shouldn't break like that though. I made a ticket over at #12 for this.

**Comment by waywardm** [comment]
the script file exists at the same same default path as it was pulled down from github the only thing i have changed are the shopify id etc in the slater config, it maybe just a windows issue but i’m not knowledgable enough to be able to troubleshoot the issue

Regards

Paul Kidd


Thunderfix

________________________________

**Comment by estrattonbailey** [comment]
@waywardm in 76f094c I made some quick checks to ensure the filepath is output from our watch handler, which might help. 

Also, I added a `--debug` flag to the CLI that will log the entire computed `slater.config.js` on `watch` and `build`.

Can you `npm i slater@1.3.3 --save` and then update your start script to `slater watch --debug` and shoot us a screenshot of the CLI output?

**Comment by waywardm** [comment]
**Below is steps taken as above and then a small alteration to a file to cause the watch to rebuild**


admin@DESKTOP-HK27D9K MINGW64 /s/shopify/slaterthunderfix
$ yarn add slater@1.3.3
yarn add v1.12.3
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.8: The platform "win32" is incompatible with this module.
info "fsevents@1.2.8" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning "slater > @friendsof/spaghetti > postcss-cssnext@3.1.0" has unmet peer dependency "caniuse-lite@^1.0.30000697".
[4/4] Building fresh packages...

success Saved lockfile.
warning "slater" is already in "devDependencies". Please remove existing entry first before adding it to "dependencies".
warning Your current version of Yarn is out of date. The latest version is "1.15.2", while you're on "1.12.3".
info To upgrade, download the latest installer at "https://yarnpkg.com/latest.msi".
success Saved 3 new dependencies.
info Direct dependencies
└─ slater@1.3.3
info All dependencies
├─ @slater/compiler@1.3.3
├─ @slater/sync@1.3.3
└─ slater@1.3.3
Done in 89.79s.

admin@DESKTOP-HK27D9K MINGW64 /s/shopify/slaterthunderfix
$ yarn start
slater v1.3.3

debug {
  "in": "S:\\shopify\\slaterthunderfix\\src",
  "out": "S:\\shopify\\slaterthunderfix\\build",
  "assets": {
    "in": "/src/scripts/index.js",
    "alias": {
      "@": "S:\\shopify\\slaterthunderfix\\src\\scripts"
    },
    "presets": [
      "maps",
      "postcss"
    ],
    "out": "\\build\\assets"
  },
  "themes": {
    "development": {
      "id": "71754317889",
      "password": "5cdeb51a2573f91df05649c596a8eab0",
      "store": "thunderfixhardware.myshopify.com",
      "ignore": [
        "settings_data.json",
        "**/scripts/**",
        "**/scripts",
        "**/styles/**",
        "**/styles",
        "DS_Store",
        "*.yml",
        ".DS_Store",
        "node_modules"
      ],
      "name": "development"
    }
  },
  "theme": {
    "id": "71754317889",
    "password": "5cdeb51a2573f91df05649c596a8eab0",
    "store": "thunderfixhardware.myshopify.com",
    "ignore": [
      "settings_data.json",
      "**/scripts/**",
      "**/scripts",
      "**/styles/**",
      "**/styles",
      "DS_Store",
      "*.yml",
      ".DS_Store",
      "node_modules"
    ],
    "name": "development"
  }
}
watch development theme (https://thunderfixhardware.myshopify.com/?fts=0&preview_theme_id=71754317889)

path.js:39
    throw new ERR_INVALID_ARG_TYPE('path', 'string', path);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type object
    at assertPath (path.js:39:11)
    at Object.join (path.js:434:7)
    at formatFile (S:\shopify\slaterthunderfix\node_modules\slater\index.js:52:16)
    at FSWatcher.chokidar.watch.on.on.file (S:\shopify\slaterthunderfix\node_modules\slater\index.js:175:22)
    at FSWatcher.emit (events.js:182:13)
    at FSWatcher.<anonymous> (S:\shopify\slaterthunderfix\node_modules\chokidar\index.js:199:15)
    at FSWatcher._emit (S:\shopify\slaterthunderfix\node_modules\chokidar\index.js:241:5)
    at FSWatcher.<anonymous> (S:\shopify\slaterthunderfix\node_modules\chokidar\lib\nodefs-handler.js:274:18)
    at FSReqWrap.oncomplete (fs.js:159:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

admin@DESKTOP-HK27D9K MINGW64 /s/shopify/slaterthunderfix
$

**Comment by estrattonbailey** [comment]
@waywardm what version of node are you on?

Also, maybe this has something to do with it? https://github.com/yarnpkg/yarn/issues/5115

This error `fsevents@1.2.8: The platform "win32" is incompatible with this module` still makes me wonder if it has something to do with Windows that I'm not aware of.

**Comment by waywardm** [comment]
node 10.7.0

i run gatsbyjs as an example and it always highlights fsevents as an error, i just tried an npm install instead of yarn and it is still throwing the same errors

it seems to me that is just does not like the path

**Comment by waywardm** [comment]
is it missing some aliases in the webpack config possibly

**Comment by estrattonbailey** [comment]
@waywardm good thought, but I'm thinking no, because there are no aliases used internally. The error – according to those traces – is coming from [this line](https://github.com/the-couch/slater/blob/master/packages/slater/index.js#L52), and originating from the call to `formatFile` [here](https://github.com/the-couch/slater/blob/master/packages/slater/index.js#L175), which points to either `file`, `config.in` or `config.out` being something other than a string.

This might take some extensive Googling, haha. Wish I had a Windows machine to test on. Quickest idea is for me to toss in a bunch more logs and have you report back on what you see. Alternatively, if you're familiar with local npm package development, I could help you get set up with a local copy of slater where you can debug from the source code. Up to you!

Thanks for being patient and helping us out on this, we really appreciate it :) we're excited to finally have people using it! It just means we actually have to put some polish into it, since prior to this it's been essentially just Kevin and I using it haha.

**Comment by waywardm** [comment]
when i was googling the other day I read something about using path resolve instead of join, i’m not familiar with npm package development, But happy to report on logs alternatively i could email you my slater config shopify password and id etc for you to run it against the theme to make sure it is not shopify that is causing the problem as when i do slater sync the files do not upload, so my thought was maybe it needs those files on the shopify server first

Regards

Paul Kidd


Thunderfix

________________________________

**Comment by estrattonbailey** [comment]
@waywardm hey there! Sorry for the delay, finally getting back to a few things.

Noticed your URLs are Windows specific i.e. `S:\shopify\slaterthunderfix\src\scripts`. Slater uses Webpack internally. Do you know if Webpack supports Windows paths like that?

Also, it may be where you're running the `slater` command from. If `slaterthunderfix` is your theme, then you should be *within* that directory when running `slater`.

If you're already doing that, can those URLs be updated to use a relative path like `./slaterthunderfix/src/scripts`?

**Comment by stefanbayjensen** [comment]
A colleague of mine was able to fix the paths problem by doing `in: "//src/scripts/index.js"`, and `out: "//build/assets/"`. 

The problem was that windows automatically would replace the first ´/´ in a line, if it wasn't followed up by another one.

But he still can't manage to get the `slater watch` or `slater sync` to work – And that's when using the same theme credentials as me (mac user)

**Comment by stefanbayjensen** [comment]
I've now fixed the issue with `slater watch`, not wanting to watch the files – I've tested this solution on both macOS and Windows

```
function formatFile (filepath, src, dest) {
  if (!filepath) return {}

  const filename = `./${path.relative(dest, filepath)}`

  return {
    filename,
    src: filepath,
    dest: path.join(dest, filename)
  }
}
```

The only remaining problem now is, that it's unable to sync the files on Windows. I can see that it's reloading the preview-window as it should, but it isn't syncing the files.

Windows syncing output is following:
```
watch development theme (xxxx)

syncing nothing was synced
synced assets/index.js
built in 2.659s
  > index.css
  > index.js
```

**Comment by waywardm** [comment]
i’m glad you are managing to find a solution for this issue as I desperately want to use this solution.

Regards

Paul Kidd


Thunderfix
________________________________

**Comment by entozoon** [comment]
I found the same issue on Windows. Paths are "\\" throughout, rather than "/" as node expects.
Created a PR (referenced above ^) to fix the issue where noticed. It then watches and syncs files as expected.

**Comment by entozoon** [comment]
That said, it doesn't build. So that'll need fixing as well. Not sure if I have the resources to do it myself right now

**Comment by iamkevingreen** [comment]
can someone on window confirm the merge worked? @entozoon @waywardm ? 🍝

**Comment by entozoon** [comment]
Would be a little bias for me to confirm it, but I believe so. Thanks for merging!
Live reload still isn't playing nicely though, and no doubt more further issues so I ended up building and migrating to my own toolkit, no offense, just needed to fulfill our tooling requirements quickly:
https://github.com/entozoon/slatest

**Comment by iamkevingreen** [comment]
@entozoon I can't believe you called it slatest. I'm dying 👍

**Comment by entozoon** [comment]
I, hah, yeah I didn't exactly want to but.. couldn't not. I mean, it seems to be the naming convention in a way! Not sure what'd be next. Slatomorrow ? oof

**Comment by dav11d** [comment]
@iamkevingreen 1.5.3+ just killed my setup on windows subsystem for linux.

Path error on finding the entry index.js have tried replace ./ etc
