### ISSUE TITLE
Theme: Product page: Quantity buttons don't work

### ISSUE THREAD

**Issue by tomaszbujnowicz** [the-couch/slater#13]
First of all, well done guys. 
It's really nice to see some alternative to recently not supported Slate.

So, it seems that quantity buttons on the product page don't work. They do work on the cart overlay though.
I am pretty sure you are aware of that issue, here is the screenshot https://take.ms/UzaYe

**Comment by seandogg** [comment]
@tomaszbujnowicz if you needed a quick fix, you can add `class="js-add-single"` and `class="js-remove-single"` to line12 and line10 of `snippets/component-counter.liquid`

I agree kudos to these guys for this project, it's great. And I'll let them reply how to best fix this, not sure if my logic is optimal, but it seems to work nonetheless...

**Comment by iamkevingreen** [comment]
I really thought I fixed that when i did my sweep! I'll get that in there and make the price increment as well

**Comment by seandogg** [comment]
> @tomaszbujnowicz if you needed a quick fix, you can add `class="js-add-single"` and `class="js-remove-single"` to line12 and line10 of `snippets/component-counter.liquid`

^ this isn't working for me after today's release... just in case anyone goes trying, probably better to hold off

**Comment by tomaszbujnowicz** [comment]
Ok, I think I was able to fix that in the following pull request https://github.com/the-couch/slater/pull/25

Tested with different products, variants, etc.. and it seems to work just fine.

**Comment by estrattonbailey** [comment]
@tomaszbujnowicz thanks for this PR btw! Gonna close this. Can reopen if the issue continues.

@all-contributors please add @tomaszbujnowicz for code
