### ISSUE TITLE
Slater still attempting to connecto to localhost on a production build

### ISSUE THREAD

**Issue by joniler** [the-couch/slater#130]
For some reason, when I deploy to production, slater still seems to want to act like it's in development mode. It keeps trying to connect to localhost. In its attempt, it seems to be slowing down the pages time to interactivity. Is there any way to stop this, or is this always there?

![Screen Shot 2021-03-10 at 7 43 32 AM](https://user-images.githubusercontent.com/16842926/110658400-83113880-8176-11eb-9b8a-36676aa16bcc.png)

**Comment by seandogg** [comment]
@joniler I get this if I run a watch and cancel it, without running a deploy. Running another deploy fixes it for me. I am running `npm run deploy:production` in my case.

**Comment by joniler** [comment]
@seandogg When I run that I get this:

<img width="1477" alt="Screen Shot 2021-03-10 at 8 16 06 AM" src="https://user-images.githubusercontent.com/16842926/110660942-ed2add00-8178-11eb-8d72-a9aa3399ae99.png">

**Comment by joniler** [comment]
@seandogg It's still appearing even when I run that command as well. It appears no matter what when I run `slater build && slater sync --theme themeName`

**Comment by seandogg** [comment]
@joniler assuming you've done the `rm -rf node_modules/` with a fresh `npm install` that's one thing to try, also curious what version of node you're using? I've seen this before and trying to remember what fixed it. Might have been a node version.. 

`node -v` should output the version

**Comment by joniler** [comment]
I haven't done a reinstall in a while... but I can try that. It hasn't been long since I did that though, not sure how much it's going to change.

Running v12.19.0

**Comment by seandogg** [comment]
@joniler I am on node v15.3.0 here, might be one to consider. However if you can deploy to other projects might not be the issue.

**Comment by jack-pallot** [comment]
I'm seeing the same thing on my copy where the production flag doesn't seem to change the JS bundle. @joniler if you look at your production JS bundle, is it minified for you, or not?

**Comment by joniler** [comment]
I've figured it out on my end! The issue was that I was running:
`slater build && slater sync --theme testing`
Instead of:
`slater build --theme testing && slater sync --theme testing`

It wasn't actually properly compiling my code before deploying with sync, so slater was wigging out. I feel like the docs should be updated to let people know that there are also build flags, because I didn't see that (though it should have been obvious to me that it needed to know which theme I wanted to build 🙄).

My setup has a couple of dev theme configs, testing, and production. We also have Tailwind set up in the `slater.config.js`, so we have to track it in version control. We also have CI/CD pipelines, and it was failing to build there mysteriously as well... 

Using this command solved all my issues. 

Thanks for the help @seandogg & @jack-pallot!
