### ISSUE TITLE
Theme: Pagination on the collection page doesn't work

### ISSUE THREAD

**Issue by tomaszbujnowicz** [the-couch/slater#18]
I suspect it has something to do with router.js
When we disable routing in the index.js then pagination works just fine.

**Comment by Jore** [comment]
Hi @tomaszbujnowicz, I encountered the same problem and found it was a bug in the [https://github.com/estrattonbailey/operator/pull/12](operator) dependency. I have created pull request for slater to use the fixed version of `operator`. Hopefully, it's merged soon!

**Comment by estrattonbailey** [comment]
Y'all are fantastic, thanks for the diligence on these! Once #19 is merged I imagine we'll be able to close this one.

**Comment by seandogg** [comment]
works swimmingly for me after updating to 1.4.0

**Comment by tomaszbujnowicz** [comment]
Yes, I can confirm that it works as it should now ;)
