### ISSUE TITLE
Cannot read property 'cart' of undefined after recent update

### ISSUE THREAD

**Issue by tomaszbujnowicz** [the-couch/slater#22]
It seems that some things don't work after recent pull https://github.com/the-couch/slater/pull/19

I got this https://take.ms/GuDBA
`Cannot read property 'cart' of undefined`

I also tried to make a clean install and got the same error.

**Comment by Jore** [comment]
Hey mate, thanks for reporting. I will look at this now.

**Comment by Jore** [comment]
See pull request #23. If you check the code out, you'll see the state api has changed. See [picoapp](https://github.com/estrattonbailey/picoapp/) readme for updated usage guide.

**Comment by tomaszbujnowicz** [comment]
Thanks @Jore 

https://github.com/the-couch/slater/pull/23
I was just about to create a pull request with the same changes ;) 
I can confirm that It does the trick.

When this is merged, we can close the issue.
