### ISSUE TITLE
Can't include SVG in the scss

### ISSUE THREAD

**Issue by tomaszbujnowicz** [the-couch/slater#27]
It seems that we can't use SVGs (from Assets folder) in the scss file. There is an error in the Webpack saying:
`Module build failed (from /Users/.../.nvm/versions/node/v8.16.0/lib/node_modules/slater/node_modules/@slater/compiler/node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleNotFoundError: Module not found: Error: Can't resolve './icon-down.svg' in '/path_to_css/styles'`

I've tried different assets path combination but none of them worked.

Until this is fixed here is my workaround: https://stackoverflow.com/a/21626701/5664137
Just convert SVG source to Base64 format (using e.g. https://www.base64encode.org/) and then include in the scss file as 
background-image: url("data:image/svg+xml;base64,YOUR_CODE_HERE");

**Comment by estrattonbailey** [comment]
@tomaszbujnowicz I'm not sure how Webpack attempts to resolve static assets within stylesheets, but I would imagine that a `../../` kind of thing *should* work, but not sure. Regardless, if you're trying to get the Shopify CDN URL, you're gonna run into the same issue as in #4. 

Basically, we'd need to find a good way to generate those URLs and replace them throughout the codebase. Not sure we've ever seen that done in any other library, but it could be possible!

**Comment by Jore** [comment]
I typically just avoid including any assets in the stylesheets and in the case of svgs just create a snippet liquid file per svg. I do agree in looking into possible solutions I’m sure there are use cases I haven’t come across.

**Comment by estrattonbailey** [comment]
@tomaszbujnowicz yeah after taking some more time to think about it, I think we should avoid adding extra complexity to the build step and keep things simple. Here are the current options:

1. upload your SVGs to the assets or Files interface and copy/paste the full URL
2. as Jore said, create separate SVG.liquid snippets
    - this way also allows for CSS styling, which is a big plus in my book
3. inline them as you are
    - I only recommend doing this for very small icons, for byte size reasons
