### ISSUE TITLE
Issue when using ENV vars in JS

### ISSUE THREAD

**Issue by wardpenney** [the-couch/slater#28]
Hi team, migrating to Slater today. It is really wonderful, thank you for making this. I am attempting to use the ENV variable feature, and I'm either using it wrong or there is an issue. After installing the initial Slater `init` project, and setting up my development store settings, I made these changes:

Updated `slater.config.js` to include an `env` object (the `...` are real values pointing to my development store):

```
const path = require('path')

module.exports = {
  themes: {
    development: {
      id: '...',
      password: '...',
      store: '...',
      ignore: [
        'settings_data.json' // leave this here to avoid overriding theme settings on sync
      ]
    }
  },
  env: {
    TESTVAR: 'testing the env'
  }
}

```

Then in `src/scripts/index.js` file I added the following at the bottom:

```
console.log("hey yo");
console.log(TESTVAR);
```

**Bug**: Console error: `Uncaught ReferenceError: TESTVAR is not defined`. The `hey yo` message does appear when previewing the theme, so I know the sync worked. I might be reading the documentation improperly, and I couldn't figure out where to find how this is performed in the source.

Any help would be appreciated! Thanks.

**Comment by estrattonbailey** [comment]
@wardpenney good catch! Currently working towards a test suite for a lot of this stuff. I'm not sure where that's getting missed at the moment, but can probably have a look this weekend.

If you feel like taking a stab at debugging, I've just added contributing instructions to the repo! (I think those should be comprehensive 🤔) https://github.com/the-couch/slater#contributing

**Comment by wardpenney** [comment]
@estrattonbailey it took some tracking, but I found out what was happening. See the PR ^.

They key point was when Slater application passes only the `assets` portion to the compiler app https://github.com/the-couch/slater/blob/master/packages/slater/index.js#L92

Ideally, this probably isn't the best since ENV vars aren't really assets. But, not huge deal, as long as the docs are correct. 

Thanks!

**Comment by estrattonbailey** [comment]
@wardpenney brilliant, thank you! Just merged. Really appreciate the help!

Yeah re: "assets", it's referring to the JS and CSS. Maybe we should rethink that naming convention...

**Comment by estrattonbailey** [comment]
@all-contributors please add @wardpenney for bug and doc
