### ISSUE TITLE
CLI command to switch between CSS/Sass

### ISSUE THREAD

**Issue by mrtamagotchi** [the-couch/slater#48]
As an avid SCSS user I'm super happy that you have chosen to include Sass-support with a simple change in the config file, makes it much easier for me to work with my beloved functions and mixins. However there is one tedious thing keeping me from a smooth workflow if I want to use the nice bootstrapping provided with Slater - renaming all`.css` to `.scss`, both in filenames and `@import`. 

I propose a new command: `slater config --styles=<css|sass|scss>`. This would update the assets preset in `slater.config.js` with either `css` or `sass` and all filenames and `@import` to `.css`, `.sass` or `.scss`. (note: I have yet to meet a developer who prefers Sass over SCSS, but its nice to have that support anyways)

This would save a lot of time during startup, and also probably be quite fun to code!

`slater config` could also be extended in the future for other similar tasks.

Thoughts?

**Comment by iamkevingreen** [comment]
@mrtamagotchi I 100% support this, anyone willing to PR this I welcome. I'll continue to be a postcss boi and more so headless/sdk Shopify based so if someone builds it, i'll merge it ;)
