### ISSUE TITLE
Add to cart doesn't work for related products on the product page

### ISSUE THREAD

**Issue by tomaszbujnowicz** [the-couch/slater#49]
I have the related products section on the product page and these related products have the “add to cart” button enabled. For some reason, I got the following JS error:
https://take.ms/hVTye

The temporary fix suggested by @mrtamagotchi  is to change the policy for the products so that they wouldn't sell after they went out of stock.

It would be nice to find a more stable fix for that issue.

**Comment by iamkevingreen** [comment]
realized the fix flag didn't properly close this back when it was merged.
