### ISSUE TITLE
picoapp - cartDrawerItem failed

### ISSUE THREAD

**Issue by alejuu** [the-couch/slater#5]
Hi,
I'm testing slater, and I love it! But, I'm getting an issue when I click the cart button, it opens the sidebar correctly, but I get this error on the console:
```picoapp - cartDrawerItem failed - Cannot read property 'getElementsByTagName' of undefined
bootstrap:2 TypeError: Cannot read property 'getElementsByTagName' of undefined
    at bootstrap:2
    at bootstrap:2
    at Object.mount (bootstrap:2)
    at bootstrap:2
```
Also, I can't change the quantity of the products that I have in my cart.

Thanks!

BTW this is also happening in your demo site https://slater-demo.myshopify.com/

**Comment by callumflack** [comment]
Slater looks great. You may start getting a number of folks checking it out b/c of the "low maintenance" status of Slate (WTF?). 

However, when I followed up on this, and tried checking out, I get a bunch of liquid snippet errors:

![image](https://user-images.githubusercontent.com/749885/55840583-3a5a3a80-5b6f-11e9-91d8-4326f7fe1a78.png)

But I'd say everything does work b/c your "In the wild" sites don't bug out. It'd be great to have a fresh, working repo though 😊

**Comment by iamkevingreen** [comment]
@callumflack & @alejuu The theme part is a bit of a frankenstein right now. We've renamed things here and there and adjusted some cart things and it just hasn't all ended back into the repo. We're looking to refactor that this weekend! The `form-input-text.liquid` for example is in there it's just now named `input-text.liquid`. We'll PR fix these soon, our struggle is trying not to make the cart too opinionated, but... we'll have to put some opinions in there if we want to have a working ajax cart :)
