### ISSUE TITLE
Fix fatal error handling

### ISSUE THREAD

**Issue by estrattonbailey** [the-couch/slater#55]
If the remote theme doesn't exist, @slater/sync fails with an unhelpful message. Looks like it's the error handling in both the entry file and the cli. Error is like `can't read property asset of undefined`.

**Comment by ca-miked** [comment]
I'm hitting this error, in a new test store. Any advice on a workaround? I basically took the default theme and duplicated it per [this article](https://medium.com/the-couch/getting-started-with-slater-bundling-and-deployment-with-any-existing-shopify-theme-d994a17f590f) . Get the following error when running "deploy:development"

```bash
slater v1.7.1

slater syncing

🏡  ························📦  🌍  100%
(node:11462) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'asset' of undefined
    at wait.then.catch (/Users/xxx/xxx/xxx/xxx/node_modules/slater/cli.js:78:53)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:11462) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function wit
hout a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 97)
(node:11462) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will 
terminate the Node.js process with a non-zero exit code.```

**Comment by estrattonbailey** [comment]
I don't remember exactly what this issue was about, but re: my initial posting, have you double-checked that your theme ID, password, and shop URL are correct?

Otherwise, another thing it might be is a file that isn't a valid theme file exists in a theme directory i.e. `/snippets/header.txt` where only `.liquid` files should live.

**Comment by ca-miked** [comment]
Ahh, `id` was the issue in the slater.config.js. I had the API key in there instead of the theme id. Thanks for the assistance!
