### ISSUE TITLE
Firing Shopify Trekkie (Facebook/GA/Tracking Scripts) on route change

### ISSUE THREAD

**Issue by aeblin** [the-couch/slater#65]
This is more a "How have you all handled this?" than a bug, but I'm curious to hear how anyone using Slater has managed to handle the fact that the Trekkie scripts don't treat route changes as page loads, and tend not to fire as a result.

**Comment by iamkevingreen** [comment]
@aeblin So we've done it a few ways, since picoapp remounts the application, you could do it at a page level with a helper component specifically for firing tracking, we additionally pass more information on a product level. It does require a bit of extra (check if script is on the window) fact checking though fro some. using the react-ga and react-fb-pixel lib are great, and if you have the chance to use segment/GTM you can just track the data in one place from a code perspective.

**Comment by aeblin** [comment]
@iamkevingreen Thanks for the reply! What I'd wound up doing specifically for the facebook pixel was throwing the tracking event call I wanted for product pages within the product.js component file, as I knew it'd fire there when routed to. The helper component is a great idea, as well, and a good bit cleaner.

The issue I'm running into is mostly with regard to trekkie specifically, though. Shopify inserts that code into the head of the site regardless of what's in the theme, if there's a value input for Google Analytics or the Facebook Pixel in the Shopify admin panel. Since Trekkie is always in the head, it has trouble with the picoapp mounting/routing, and I can't seem to find a function to call on route change to get trekkie to fire/instantiate. 

If I'm reading your reply right, it sounds like you all tend to just navigate around trekkie entirely in favor of putting GA and the FB Pixel in manually? That said, the Dims site seems to have the Trekkie script included.

**Comment by iamkevingreen** [comment]
@aeblin speaking of dims, on 'after' render we do indeed track all the things, eric wrote a nice little helper for this:

```js
  analytics({
    ga: ['set', 'page', pathname],
    ga: ['send', 'pageview'],
    fbq: ['track', 'PageView']
  })
```

then the analytics.js file:
```js
export default function track (events = {}) {
  for (let service in events) {
    const fn = window[service]

    if (!fn) continue

    fn.apply(this, events[service])
  }
}
```

**Comment by aeblin** [comment]
@iamkevingreen That's a great little snippet, going to implement something similar! Does this seem too niche to consider including by default in the starter theme?

**Comment by iamkevingreen** [comment]
@aeblin I think it might be nice to show it as a use case, I am about to do another large shopify build so will probably dump some updates in the theme ;)

**Comment by sampsonpete** [comment]
I’d definitely be keen to see a full example of how to implement this as it’s a key feature for any theme.
