### ISSUE TITLE
npm not updated for v.1.6.0

### ISSUE THREAD

**Issue by stefanbayjensen** [the-couch/slater#66]
Hello i just realised this bug, when trying to test the _window-fix_, and i couldn't seem to get it working. Then i realised that it was the v.1.5.3, it kept installing from the npm-server :)

**Comment by jonathanmoore** [comment]
I'm running into the same issue.  It seems like there was some problems with slater/sync in 1.5.3, and I'm unable to install the latest 1.6.0.

**Comment by iamkevingreen** [comment]
@jonathanmoore @stefanbayjensen sorry about that, lerna will one day agree with me. 1.6 should now install
