### ISSUE TITLE
Redirect to collections as landing page

### ISSUE THREAD

**Issue by scottyeung** [the-couch/slater#68]
I tried to import app.js and use `app.go('collections/all')` in my slater-welcome.js to redirect to collections page, but it said app.go is not a function. Can anyone help to point out the right way for redirection?

**Comment by chrismlusk** [comment]
Hi @scottyeung. If you imported `app.js`, then `app` references the `picoapp` instance, not the `operator` instance. Try this instead:

```js
import router from '@/router.js'
```

**Comment by scottyeung** [comment]
You're magical! Thank you
