### ISSUE TITLE
Issue with Outputs 

### ISSUE THREAD

**Issue by jrandallw** [the-couch/slater#71]
Hey, y'all. First off, this tool is amazing, makes theme development so much better.

I am developing a store for a client, and they have products with multi-word color variations, i.e. Melted Chocolate, Salted Green, etc. The radio inputs on product pages are outputting the values in strange ways, making the second word in the product name an attribute on its own, which fails to update the select box. It's kind of convoluted explaining it in words, but here is the HTML that it's spitting out. 

```
<label class="radio f aic">
    <input id="Melted" chocolate="" type="radio" name="Color" value="Melted" chocolate checked>
    <span>Melted Chocolate</span>
</label>
```

I need it to output like so:

```
<label class="radio f aic">
    <input id="Melted Chocolate" type="radio" name="Color" value="Melted Chocolate" checked>
    <span>Melted Chocolate</span>
</label>
```

But I'm failing to find where the problem lies. Anyone have any solutions?

**Comment by tomaszbujnowicz** [comment]
This is what worked in my case:
1. open /src/snippets/component-radio.liquid
2. add ' (quote) to id, name, and value so it looks like

`
  <input
    id='{{label}}'
    name='{{name}}'
    value='{{value}}
    ....
`

**Comment by jrandallw** [comment]
That worked perfectly. Thank you!
