### ISSUE TITLE
Issues with quantity in cart drawer

### ISSUE THREAD

**Issue by jrandallw** [the-couch/slater#72]
I'm having an issue where the quantity buttons, `js-remove-single` and `js-add-single` in the cart drawer are not functioning properly. `js-add-single` is removing quantities, and `js-remove-single` is removing more than one item. Has anyone else had this issue and has anyone had any ideas on how to fix?

My dev shop is [here](https://serman-brands-inc.myshopify.com/products/the-elite).

Thanks,
Jesse

**Comment by jrandallw** [comment]
Hi there! Any updates on this? Thanks!

**Comment by stefanbayjensen** [comment]
Hello @jrandallw,
Is it possible for you to upload the project to Github, so people can review your code? I've done the quantity-select multiple times in the cart drawer, and i've been working every time 😄

**Comment by jrandallw** [comment]
It's just started working again for me, maybe it was something in my build... thanks for your time!
