### ISSUE TITLE
Slater not able to sync the checkout.liquid for Plus merchants

### ISSUE THREAD

**Issue by stefanbayjensen** [the-couch/slater#77]
I recently discovered that it's not possible to sync the **checkout.liquid**-file via the slater cli – This made me think about how to fix this issue, and after reading the Shopify assets api docs, I found a way to do so.

The problem is currently that the `function upload()` in `@slater/sync/index.js`, is base64 encoding the liquid files, and deploying them via the attachment key.

```
function upload ({ key, file }) {
    const encoded = Buffer.from(fs.readFileSync(file), 'utf-8').toString('base64')

    return api('PUT', {
      asset: {
        key,
        attachment: encoded
      }
    })
    ...
}
```

The problem with this is, that Shopify is expecting the liquid input as a normal string, and via the value key, as in [this example](https://help.shopify.com/en/api/reference/online-store/asset#update-2020-01) – So a possible fix, could be changing the upload function to this:

```
function upload ({ key, file }) {
    const encoded = Buffer.from(fs.readFileSync(file), 'utf-8').toString('base64')
    const value = Buffer.from(fs.readFileSync(file), 'utf-8').toString()

    const output = key.includes('.liquid') ? { key, value } : { key, attachment: encoded }

    return api('PUT', {
      asset: output
    })
    ...
}
```

These changes has been tested, and are working.

**Comment by iamkevingreen** [comment]
🙏 Honestly I didn't even consider this was a sync issue and accepted it as a Shopify issue in general. I've pushed this into sync have it operating as expected in my own environment!
