### ISSUE TITLE
Product Page: Default variant unselected

### ISSUE THREAD

**Issue by artshostak** [the-couch/slater#80]
It appears that with a flat product, that doesn't have any variants, the "select" doesn't default to the only available option. This is straight out of the box, and can be seen in your demo:
https://slater.store/collections/frontpage/products/sale-product

Wondering if that's come up before, and if so, what the best way to resolve that is — since ideally this will be visually hidden since it doesn't require user input. Thank you!

![Screen Shot 2020-02-09 at 11 20 21 AM](https://user-images.githubusercontent.com/6820356/74108333-2d5efc80-4b2e-11ea-803c-e912358aa97c.jpg)
![Screen Shot 2020-02-09 at 11 20 36 AM](https://user-images.githubusercontent.com/6820356/74108342-35b73780-4b2e-11ea-8a2f-9965f31200ce.jpg)

**Comment by seandogg** [comment]
@artshostak I'm not totally certain, but I've been using that select box (with multiple variants) as a reference during development for what will actually be sent to the cart. I then hide that select with css. I use it as a source of truth per se. (Especially helpful with multiple variants)...

**Comment by iamkevingreen** [comment]
@artshostak The reason this approach is extremely minimal is that nearly all the sites we built as the couch/with slater require different variant selection, some color pickers, some box size selectors, honestly rarely drop down selectors. You could resolve this forcing a select event if you wanted to use the default selector, but the point of this aspect of the theme is to show a minimal custom select experience. This theme isn't meant to really work for every situation but more get in the way so every situation can be implemented.

**Comment by bekahmcdonald** [comment]
For me, even though I'm hiding the `[data-option-main]` select, and using it as a source of truth like @seandogg, the fact it's blank on page load has been causing problems for products that only have one variant, particularly around inventory management.

The line that seems to be causing this issue is in the `updateSelection()` function in `scripts/lib/options.js`.

```javascript
function updateSelection() {
    state.id = variants[state.options.join(' / ')];
    main.value = state.id; // For products with only one variant, state.id is undefined
    for (let fn of listeners) fn(state);
 }
```

I've managed to get around this so far by checking the value of `state.id` before assigning it to `main.value`.

```javascript
function updateSelection() {
    state.id = variants[state.options.join(' / ')];
    main.value = state.id || main.value; // Prevent 'undefined'
    for (let fn of listeners) fn(state);
}
```
