### ISSUE TITLE
Curious if anyone has added line item properties to cart.js?

### ISSUE THREAD

**Issue by seandogg** [the-couch/slater#82]
Was looking to send some custom engraving info via [line item properties](https://ui-elements-generator.myshopify.com/pages/line-item-property)

Struggling to add it to the existing `cart.js` and was wondering if anyone has added this? I tried using liquid but the `preventDefault` in `product.js` prevents that data from being sent, so I'm guess we need to add this in our JS

Edit: apologies as this isn't a true "issue" with this repo, rather a how-to... and possibly a PR if it would benefit everyone?

**Comment by iamkevingreen** [comment]
@seandogg you could add custom attributes to the AddVariant function which is called here:

https://github.com/the-couch/slater/blob/e0ca96d1998e2e7657c2e1de83fd9b6f6a5f3884/packages/theme/src/scripts/components/product.js#L15

and then in here: https://github.com/the-couch/slater/blob/master/packages/theme/src/scripts/lib/cart.js right now we're only sending the variant and the quantity, you can append the addItemById to also pass a custom attribute to the ajax function: https://github.com/the-couch/slater/blob/e0ca96d1998e2e7657c2e1de83fd9b6f6a5f3884/packages/theme/src/scripts/lib/cart.js#L57

You can pass a `properties` object of keys + values: https://shopify.dev/tutorials/develop-theme-getting-started-using-ajax-api#add-to-cart
