### ISSUE TITLE
Google Lighthouse Audit Query

### ISSUE THREAD

**Issue by waywardm** [the-couch/slater#9]
I’m looking into this as a basis of transferring the shopify supply theme to, which i have on the old slate version however when i have ran a lighthouse audit on the four examples shown the all score really badly on performance at about 30%. The examples appear really fast but why does google audit think differently.

**Comment by estrattonbailey** [comment]
@waywardm sorry for the confusion!

Slater is _only_ focused on the compilation and deploy process of Shopify theme development. The examples in the README are entirely custom, though they were built and compiled using Slater. Their Lighthouse score has nothing to do with Slater at all, and entirely how the sites themselves where built (React, big images, etc).

@iamkevingreen maybe we should just remove those examples? They're not really indicative of what Slater does.

**Comment by iamkevingreen** [comment]
I think it's nice to know that the theme is actually used in the wild. Might encourage people to share sites and actually use it 🌮 

@waywardm running a lighthouse audit on the example theme (which is now linked in the header of the repo) returns the following:

![Screen Shot 2019-04-27 at 5 32 41 PM](https://user-images.githubusercontent.com/2124358/56855286-9a443580-6912-11e9-9076-3712c1b5c9a6.png)

As Eric said, the sites you referenced have various other factors adding to the bloat of a lighthouse score.
