### ISSUE TITLE
Sold Out products?

### ISSUE THREAD

**Issue by fowlercraig** [the-couch/slater#94]
Is there any documentation explaining how to alert customers that a product is Sold Out?

**Comment by iamkevingreen** [comment]
this isn't functionality that is supported in shopify without external code, [klaviyo has a sold out ](https://help.klaviyo.com/hc/en-us/articles/360001895651-Install-Back-in-Stock-for-Shopify) pattern, there is also documentation in general [shopify](https://community.shopify.com/c/Shopify-Design/Product-pages-Allow-pre-orders-for-products/m-p/616469) for capturing an email. 

If you wish to simply show a product is sold out then use [product available ](https://shopify.dev/docs/themes/liquid/reference/objects/product)
